using UnityEngine;

[CreateAssetMenu(fileName = "NoiseSettings", menuName = "Only The Shadows Know/Noise Settings")]
public class NoiseSettingsSO : ScriptableObject
{
    [Header("Movement Noise")]
    [Tooltip("Noise generated per second while walking.")]
    public float walkNoise = 25f;
    [Tooltip("Noise generated per second while running.")]
    public float runNoise = 50f;
    [Tooltip("Noise generated by a single jump.")]
    public float jumpNoise = 40f;
    [Tooltip("Noise generated by a single jump.")]
    public float jumpRunningNoise = 60f;
    [Tooltip("Noise generated by landing after a jump.")]
    public float landNoise = 60f;
    [Tooltip("Noise generated by a dodge roll.")]
    public float dodgeRollNoise = 35f;
    [Tooltip("A multiplier for noise generated while crouching (e.g., 0.5 for 50% less noise).")]
    public float crouchNoiseModifier = 0.5f;

    [Header("Combat Noise")]
    [Tooltip("Noise generated by a single dagger slash.")]
    public float daggerAttackNoise = 15f;
    [Tooltip("Noise generated by firing the bow.")]
    public float bowFireNoise = 30f;
    [Tooltip("Noise generated by Soul Sever Ranged")]
    public float animancyRangedAttackNoise = 30f;
    [Tooltip("Noise generated by Soul Sever Melee.")]
    public float animancyMeleeAttackNoise = 30f;

    [Header("Skill Noise")]
    [Tooltip("Noise generated by using Spectral Shift.")]
    public float spectralShiftNoise = 70f;
    // We can add noise for other skills here later.
}
